import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex">
					<p className="fixed left-0 top-0 flex items-center align-middle w-full flex-col border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30">
						<span>
							⁺‧₊˚ You are the prettiest in the world ˚₊‧⁺
						</span>
						<span>˚₊‧꒰ა 🤎 ໒꒱‧₊˚</span>
					</p>
					<div className="fixed bottom-0 left-0 flex h-48 w-full items-end justify-center bg-gradient-to-t from-white via-white dark:from-black dark:via-black lg:static lg:h-auto lg:w-auto lg:bg-none">
						<a
							className=" flex place-items-center gap-2 p-8  lg:p-0"
							href="https://www.instagram.com/reel/C6BzSIyPJTY-SC6wbKb6GOc-C2Xhb7N-XzVAgI0/"
							target="_blank"
							rel="noopener noreferrer"
						>
							By{" "}
							<Image
								src="/name.png"
								alt="name"
								className="dark:invert"
								width={100}
								height={24}
								priority
							/>
						</a>
					</div>
				</div>
				{children}
			</body>
		</html>
	);
}
